version: '3.8'

services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "4000:4000"
  
  app2:
    build: ./app2
    container_name: app2
    ports:
      - "4001:4001"


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

